### ISSUE TITLE
Some US workshop times display in "Daylight" time

### ISSUE THREAD

**Issue by KatieK2** [JiggyPete/global-diversity-cfp-day-site#3]
February will be "standard" time as opposed to "daylight savings time". But the times for Atlanta and Detroit are in EDT. (Minneapolis is in Standard time, but appears to go until 2 am.)

To fix: Correct times for Atlanta and Detroit

Stretch goal: Organizers shouldn't be able to use impossible time zones.

(Timezones are hard.)

**Comment by KatieK2** [comment]
Looking at the GDCFPD workshop editing UI, I see that the available timezones for US are EDT, CDT and PDT. If they were all hard-coded to standard time, that might do the trick.

**Comment by JiggyPete** [comment]
A few weeks back I removed the displayed Timezone as it seemed the quickest and easiest way to remove confusion around this as attendees will be assuming local time.
